# Generated by Django 4.2 on 2023-04-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, unique=True, verbose_name="이메일"),
                ),
                ("name", models.CharField(max_length=10, verbose_name="이름")),
                ("nickname", models.CharField(max_length=10, verbose_name="닉네임")),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "남성"), ("M", "여성"), ("X", "젠더X")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="나이")),
                (
                    "introduction",
                    models.TextField(max_length=100, verbose_name="간단 소개글"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
